# Generated by Django 2.1.3 on 2018-12-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=20)),
                ('gender', models.BooleanField()),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=20, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='classes',
            name='m',
            field=models.ManyToManyField(to='book.Teachers'),
        ),
    ]
